### ISSUE TITLE
Giving wrong bengali date

### ISSUE THREAD

**Issue by sannjayy** [sh4hids/bangla-calendar#14]
Today Date: Wed Jan 19 2022 23:07:15 GMT+0530 (India Standard Time)

Bengali Date: বুধবার, ৬ মাঘ, ১৪২৮

But this should be 5 মাঘ 

Attaching a screenshot for reference https://ibb.co/kD0pRmP ... Please look into this and give me some solution. 

https://www.bengalicalendar.com/ & https://www.bangladatetoday.com/bangla-gregorian-date-converter.php these sites are giving correct date.

**Comment by sannjayy** [comment]
const en_date = new Date();
const en_day = en_date.getDate();
const en_month = en_date.getMonth();
const en_year = en_date.getFullYear();

**Comment by sh4hids** [comment]
@sannjayy Thank you very much for sharing the issue. I have fixed the issue on PR #15. Please use [v2.0.0](https://www.npmjs.com/package/bangla-calendar/v/2.0.0). Let me know if you face any further issues.
